sudo: false

language: java

matrix:
  include:
    - jdk: openjdk11
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"

cache:
  directories:
    - $HOME/.m2/repository

before_script:
  - java -version

script:
  - mvn test

